### ISSUE TITLE
Microverse Final Capstone

### ISSUE THREAD

**Issue by Samuellekpor** [V-Blaze/GVASH-PLANES-API#17]
Link to the Front-end: https://github.com/V-Blaze/gvash-planes
Link to the Back-end: https://github.com/V-Blaze/GVASH-PLANES-API

Hello code reviewers,
We are a team of 5 persons for this capstone project: @Samuellekpor, @ginabeki, @Abdessittir, @heintayzar-hm, and @V-Blaze.

Kanban Board screenshot:
![KanbanBoard](https://user-images.githubusercontent.com/29674658/228588538-cdaa7ccd-9f87-49f8-b60c-266db3183e60.png)

Thanks

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
